### ISSUE TITLE
Write docs on Smart Contract functionalities

### ISSUE THREAD

**Issue by irene-bbox** [BalloonBox-Inc/near-oracle-contracts#10]
### Tasks
 - [ ] write `README.md` summarizing the core logic and functionalities of the smart contract
 - [ ] include a smart contract *deployment guide* for CLI as a section of the README.md file
 - [ ] write instructions to explain and execute tests for Rust smart contract
