### ISSUE TITLE
SC - initialization

### ISSUE THREAD

**Issue by irene-bbox** [BalloonBox-Inc/near-oracle-contracts#12]
#### Description
Every smart contract must be initialized to the blockchain by calling a one-time-only initialization function (which is defined inside the contract itself). 

#### Tasks
 - [x] initialize contract state as an attribute of the primary struct (singleton) of the smart contract
 - [x] write initialization function for score dict
 - [x] initialize contract on testnet, check init function is working properly
