### ISSUE TITLE
SC - timestamp logic

### ISSUE THREAD

**Issue by irene-bbox** [BalloonBox-Inc/near-oracle-contracts#13]
#### Tasks
 - [x] store block height and time as a timestamp
 - [x] implement logic to compare timestamps
 - [x] add hard constraint: do not store more than one score a month for the same user
