### ISSUE TITLE
SC - hashing using sha256

### ISSUE THREAD

**Issue by irene-bbox** [BalloonBox-Inc/near-oracle-contracts#15]
#### Description
Encrypt the score descriptive message as a *vec < u8 >* using the sha256 hash function from the sha2 cryptographic kit. Luckily, the Rust crate named *near_sdk* provides already the function sha256()

#### Tasks
 - [x] feed as function input a *String*
 - [x] convert the input *String* into a byte string of *&[u8]* using .as_bytes()
 - [x] encrypt the byte string, i.e., hash the random string of bytes *&[u8]* into a *vec < u8 >*
