### ISSUE TITLE
SC - mid dev refactoring

### ISSUE THREAD

**Issue by irene-bbox** [BalloonBox-Inc/near-oracle-contracts#17]
#### Description
Redesign and improve the contract implementing feedback received from the team after a contract design quality assurance check.

#### Tasks
 - [x] remove the `max_size` requirement for the contract, i.e., don't set an upper bound limit to the memory used by the contract
 - [x] implement a new *User* struct replacing the old *Score* struct
 - [x] remove `query_last_score()` function and use only the `query_all_scores()` function instead
 - [x] write a gasless `does_user_exist()` function to check whether we have a score record for a given user wallet address
 - [x] fix bug overwriting scores instead of appending them (prefixes for persistent collections must be **unique**)
 - [x] increment score and user counts *iff* the score got actually stored to blockchain
