### ISSUE TITLE
Smart Contract - store and query scores

### ISSUE THREAD

**Issue by irene-bbox** [BalloonBox-Inc/near-oracle-contracts#18]
#### Description
Review the Rust code implementing the basic functionalities for the NEAR smart contract: i.e., 
 - store scores to blockchain for multiple users 
 - query the score history for a specified user
 - query the state of the contract

#### Tasks
 - [x] complete the first round of development of the smart contract
 - [x] execute unit tests to verify main functionalities
 - [x] deploy this initial contract to the NEAR `testnet` and interact with it
