### ISSUE TITLE
NFT - log events

### ISSUE THREAD

**Issue by irene-bbox** [BalloonBox-Inc/near-oracle-contracts#33]
### Description
Ever wondered how the wallet knows which NFTs you own? It's all thanks to log events. Let's implement some functions that emit an event whenever an NFT is transferred, minted, or burnt.

### Tasks
- implement a function to burn NFT once the loan has been serviced (idea for future grants)
- [x] emit an event whenever the `nft_mint` function is invoked
- [x] emit an event whenever the `internal_transfer` is invoked
- [x] emit an event whenever the `nft_resolve_transfer` is invoked
