### ISSUE TITLE
NFT - approval logic

### ISSUE THREAD

**Issue by irene-bbox** [BalloonBox-Inc/near-oracle-contracts#34]
### Description
Grant approval permission to another contract to transfer NFTs

### Tasks
- [x] grant approval to a specific account
- [x] revoke approval from a specific account
- [x] revoke approval permissions from **all** accounts
