### ISSUE TITLE
NFT - minting contraints

### ISSUE THREAD

**Issue by irene-bbox** [BalloonBox-Inc/near-oracle-contracts#42]
### Tasks
Implement the following logic in the `nft_mint()` function:
 - [x] a user can mint at most X total scores
 - [x] the contract can mint and store at most Y scores
 - [x] a user can mint at most 1 score / month
 - [x] you can't mint the same score (same media url) twice -at least not for the same recipient
